
<table style="width: 100%;" class="border_frame" cellpadding="0" cellspacing="1">
	<tr>
		<td style="text-align: center;" class="border_color sredborder">
			<div class="header_text sredborder">Beta Software</div>
				<p>By using this beta software you are bound by the terms
				<a href="http://www.wowroster.net/topic226.html" target="_blank">outlined here</a>.</p>
				<p>For information on removing this message, click the link.</p>
		</td>
	</tr>
</table>
<br />
