
PvPLogData = {
	["Doomhammer"] = {
		["Drkabank"] = {
			["notifyKill"] = "none",
			["guilds"] = {
			},
			["MiniMap"] = {
				["enabled"] = 1,
				["drag"] = "CIRCLE",
				["position"] = -45,
			},
			["recordBG"] = true,
			["vendor"] = "wowroster.net",
			["dingTimeout"] = 30,
			["dingSound"] = "AuctionWindowOpen",
			["enabled"] = true,
			["dispLocation"] = "overhead",
			["notifyDuel"] = true,
			["mouseover"] = true,
			["notifyKillText"] = "I killed %n (Level %l %r %c) at [%x,%y] in %z (%w).",
			["recordDuel"] = true,
			["battles"] = {
			},
			["version"] = "2.3.7",
			["ding"] = false,
			["display"] = true,
			["notifyDeath"] = "none",
			["notifyDeathText"] = "%n (Level %l %r %c) killed me at [%x,%y] in %z (%w).",
			["notifyBG"] = true,
		},
		["Treyce"] = {
			["notifyKill"] = "none",
			["guilds"] = {
			},
			["MiniMap"] = {
				["enabled"] = 1,
				["drag"] = "CIRCLE",
				["config"] = 0,
				["position"] = -45,
			},
			["recordBG"] = true,
			["vendor"] = "wowroster.net",
			["dingTimeout"] = 30,
			["dingSound"] = "AuctionWindowOpen",
			["enabled"] = true,
			["dispLocation"] = "overhead",
			["notifyBG"] = true,
			["mouseover"] = true,
			["notifyKillText"] = "I killed %n (Level %l %r %c) at [%x,%y] in %z (%w).",
			["recordDuel"] = true,
			["battles"] = {
			},
			["version"] = "2.3.7",
			["display"] = true,
			["ding"] = false,
			["notifyDeath"] = "none",
			["notifyDeathText"] = "%n (Level %l %r %c) killed me at [%x,%y] in %z (%w).",
			["notifyDuel"] = true,
		},
		["Mspiggy"] = {
			["notifyKill"] = "none",
			["guilds"] = {
			},
			["MiniMap"] = {
				["enabled"] = 1,
				["drag"] = "CIRCLE",
				["position"] = -45,
			},
			["recordBG"] = true,
			["vendor"] = "wowroster.net",
			["dingTimeout"] = 30,
			["dingSound"] = "AuctionWindowOpen",
			["enabled"] = true,
			["dispLocation"] = "overhead",
			["notifyDuel"] = true,
			["mouseover"] = true,
			["notifyKillText"] = "I killed %n (Level %l %r %c) at [%x,%y] in %z (%w).",
			["recordDuel"] = true,
			["battles"] = {
			},
			["version"] = "2.3.7",
			["ding"] = false,
			["display"] = true,
			["notifyDeath"] = "none",
			["notifyDeathText"] = "%n (Level %l %r %c) killed me at [%x,%y] in %z (%w).",
			["notifyBG"] = true,
		},
		["Nelmart"] = {
			["notifyKill"] = "none",
			["guilds"] = {
				[""] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Dark Tide"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Protectors of the Light"] = {
					["loss"] = 0,
					["wins"] = 1,
				},
				["Mounties"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Reckoning"] = {
					["wins"] = 0,
					["loss"] = 1,
				},
				["Thralls Elite"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["ACROSS"] = {
					["wins"] = 0,
					["loss"] = 1,
				},
				["Scandalous"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Tier Zero"] = {
					["wins"] = 0,
					["loss"] = 1,
				},
				["Vindicatum"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Three Lobed Burning Eye"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Pandemonium"] = {
					["loss"] = 1,
					["wins"] = 0,
				},
				["RedPheonixClan"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Order Of Royal Blood"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["House Extaminos"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Sweaty and ready"] = {
					["loss"] = 1,
					["wins"] = 0,
				},
				["Roughnecks"] = {
					["loss"] = 1,
					["wins"] = 0,
				},
				["Blood Line"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Forsaken Destiny"] = {
					["wins"] = 0,
					["loss"] = 1,
				},
				["Hellraisers"] = {
					["wins"] = 0,
					["loss"] = 1,
				},
				["Shadow Syndicate"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Ghostnation"] = {
					["wins"] = 0,
					["loss"] = 1,
				},
				["Flesh Peddlers"] = {
					["wins"] = 1,
					["loss"] = 0,
				},
				["Icy Death"] = {
					["loss"] = 0,
					["wins"] = 1,
				},
				["Horde of Defiance"] = {
					["wins"] = 0,
					["loss"] = 1,
				},
			},
			["MiniMap"] = {
				["enabled"] = 1,
				["stats"] = 0,
				["position"] = -40.5073230837159,
				["drag"] = "CIRCLE",
				["config"] = 0,
			},
			["recordBG"] = true,
			["vendor"] = "wowroster.net",
			["dingTimeout"] = 30,
			["dingSound"] = "AuctionWindowOpen",
			["enabled"] = true,
			["dispLocation"] = "overhead",
			["notifyBG"] = true,
			["mouseover"] = true,
			["notifyKillText"] = "I killed %n (Level %l %r %c) at [%x,%y] in %z (%w).",
			["recordDuel"] = true,
			["battles"] = {
				["Murderbull"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Warrior",
					["wins"] = 5,
					["loss"] = 0,
					["realm"] = "Altar of Storms",
				},
				["Ethanatos"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 3,
					["class"] = "Warrior",
					["loss"] = 0,
					["realm"] = "Icecrown",
				},
				["Riyin"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 2,
					["class"] = "Warlock",
					["loss"] = 0,
					["realm"] = "Demon Soul",
				},
				["Lowlide"] = {
					["realm"] = "Jaedenar",
					["zone"] = "Arathi Basin",
					["loss"] = 0,
					["class"] = "Hunter",
					["wins"] = 1,
					["enemy"] = 1,
				},
				["Peytonm"] = {
					["zone"] = "Duskwood",
					["loss"] = 0,
					["class"] = "Paladin",
					["wins"] = 1,
					["enemy"] = 0,
				},
				["Rewen"] = {
					["realm"] = "Blackwing Lair",
					["zone"] = "Arathi Basin",
					["loss"] = 0,
					["class"] = "Hunter",
					["wins"] = 1,
					["enemy"] = 1,
				},
				["Rainbowsftw"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 1,
					["class"] = "Warlock",
					["loss"] = 3,
					["realm"] = "Blackwing Lair",
				},
				["Spiritblaze"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 0,
					["class"] = "Shaman",
					["loss"] = 1,
					["realm"] = "The Venture Co",
				},
				["Anubisx"] = {
					["zone"] = "Arathi Basin",
					["loss"] = 1,
					["class"] = "Rogue",
					["wins"] = 0,
					["enemy"] = 1,
				},
				["Rider"] = {
					["zone"] = "Tanaris",
					["loss"] = 1,
					["class"] = "Shaman",
					["wins"] = 0,
					["enemy"] = 0,
				},
				["Logical"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 0,
					["class"] = "Mage",
					["loss"] = 1,
					["realm"] = "Blackwing Lair",
				},
				["Dschlickone"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 1,
					["class"] = "Warrior",
					["loss"] = 0,
					["realm"] = "Aerie Peak",
				},
				["Sprowthelas"] = {
					["realm"] = "Jaedenar",
					["zone"] = "Arathi Basin",
					["loss"] = 1,
					["class"] = "Druid",
					["wins"] = 1,
					["enemy"] = 1,
				},
				["Divo"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Mage",
					["wins"] = 0,
					["loss"] = 1,
					["realm"] = "Aerie Peak",
				},
				["Katko"] = {
					["zone"] = "Arathi Basin",
					["loss"] = 0,
					["class"] = "Paladin",
					["wins"] = 1,
					["enemy"] = 1,
				},
				["Delanthalas"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 2,
					["class"] = "Warlock",
					["loss"] = 0,
					["realm"] = "Icecrown",
				},
				["Illian"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Mage",
					["wins"] = 2,
					["loss"] = 0,
					["realm"] = "Alterac Mountains",
				},
				["Hottyhunter"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Hunter",
					["wins"] = 0,
					["loss"] = 3,
					["realm"] = "Deathwing",
				},
				["Scallywag"] = {
					["zone"] = "Arathi Basin",
					["loss"] = 1,
					["class"] = "Hunter",
					["wins"] = 3,
					["enemy"] = 1,
				},
				["Lahx"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Rogue",
					["wins"] = 3,
					["loss"] = 3,
					["realm"] = "Demon Soul",
				},
				["Arri"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Priest",
					["wins"] = 1,
					["loss"] = 0,
					["realm"] = "Anvilmar",
				},
				["Mistienna"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 3,
					["class"] = "Rogue",
					["loss"] = 0,
					["realm"] = "Kel'Thuzad",
				},
				["Tirantha"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Hunter",
					["wins"] = 0,
					["loss"] = 1,
					["realm"] = "Blackwing Lair",
				},
				["Zavas"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 1,
					["class"] = "Paladin",
					["loss"] = 0,
					["realm"] = "Deathwing",
				},
				["Faelynn"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 1,
					["class"] = "Hunter",
					["loss"] = 0,
					["realm"] = "Alterac Mountains",
				},
				["Gyrrog"] = {
					["realm"] = "The Venture Co",
					["zone"] = "Arathi Basin",
					["loss"] = 1,
					["class"] = "Warrior",
					["wins"] = 0,
					["enemy"] = 1,
				},
				["Jaezred"] = {
					["zone"] = "Arathi Highlands",
					["loss"] = 0,
					["class"] = "Rogue",
					["wins"] = 1,
					["enemy"] = 0,
				},
				["Millis"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Paladin",
					["wins"] = 3,
					["loss"] = 0,
					["realm"] = "Tanaris",
				},
				["Mythology"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Priest",
					["wins"] = 0,
					["loss"] = 1,
					["realm"] = "Demon Soul",
				},
				["Darkjmont"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Hunter",
					["wins"] = 3,
					["loss"] = 5,
					["realm"] = "Blackwing Lair",
				},
				["Camotree"] = {
					["realm"] = "Blackwing Lair",
					["zone"] = "Arathi Basin",
					["loss"] = 1,
					["class"] = "Druid",
					["wins"] = 0,
					["enemy"] = 1,
				},
				["Stormbringer"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Paladin",
					["wins"] = 3,
					["loss"] = 1,
					["realm"] = "Altar of Storms",
				},
				["Popeloui"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Priest",
					["wins"] = 1,
					["loss"] = 0,
					["realm"] = "Demon Soul",
				},
				["Nyphestis"] = {
					["zone"] = "Arathi Basin",
					["loss"] = 0,
					["class"] = "Warlock",
					["wins"] = 1,
					["enemy"] = 1,
				},
				["Flags"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Rogue",
					["wins"] = 1,
					["loss"] = 0,
					["realm"] = "Jaedenar",
				},
				["Anybody"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["wins"] = 1,
					["class"] = "Warlock",
					["loss"] = 0,
					["realm"] = "Undermine",
				},
				["Rekrisha"] = {
					["realm"] = "Altar of Storms",
					["zone"] = "Arathi Basin",
					["loss"] = 2,
					["class"] = "Hunter",
					["wins"] = 0,
					["enemy"] = 1,
				},
				["Maximos"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Paladin",
					["wins"] = 1,
					["loss"] = 0,
					["realm"] = "Sentinels",
				},
				["Meatnormus"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Druid",
					["wins"] = 0,
					["loss"] = 1,
					["realm"] = "Kel'Thuzad",
				},
				["Anghelic"] = {
					["zone"] = "Arathi Highlands",
					["loss"] = 1,
					["class"] = "Rogue",
					["wins"] = 0,
					["enemy"] = 0,
				},
				["Placmatheo"] = {
					["enemy"] = 1,
					["zone"] = "Arathi Basin",
					["class"] = "Shaman",
					["wins"] = 0,
					["loss"] = 1,
					["realm"] = "Tanaris",
				},
				["Abaloz"] = {
					["zone"] = "Arathi Highlands",
					["loss"] = 0,
					["class"] = "Mage",
					["wins"] = 1,
					["enemy"] = 1,
				},
			},
			["version"] = "2.3.7",
			["display"] = true,
			["ding"] = false,
			["notifyDeath"] = "none",
			["notifyDeathText"] = "%n (Level %l %r %c) killed me at [%x,%y] in %z (%w).",
			["notifyDuel"] = true,
		},
	},
}
PurgeLogData = {
	["Doomhammer"] = {
		["Drkabank"] = {
			["PurgeCounter"] = 5000,
			["battles"] = {
			},
			["version"] = "2.3.7",
			["vendor"] = "wowroster.net",
		},
		["Treyce"] = {
			["PurgeCounter"] = 5000,
			["battles"] = {
			},
			["version"] = "2.3.7",
			["vendor"] = "wowroster.net",
		},
		["Mspiggy"] = {
			["PurgeCounter"] = 5000,
			["battles"] = {
			},
			["version"] = "2.3.7",
			["vendor"] = "wowroster.net",
		},
		["Nelmart"] = {
			["PurgeCounter"] = 5080,
			["battles"] = {
				[5011] = {
					["rank"] = "",
					["guild"] = "Sweaty and ready",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Druid",
					["win"] = 0,
					["enemy"] = 1,
					["time"] = 1175160004,
					["race"] = "Tauren",
					["name"] = "Sprowthelas",
					["honor"] = 0,
					["date"] = "03/29/07 03:20:04",
					["lvlDiff"] = -2,
					["bg"] = 1,
					["realm"] = "Jaedenar",
				},
				[5075] = {
					["realm"] = "Tanaris",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Lumber Mill",
					["class"] = "Paladin",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 7,
					["race"] = "Blood Elf",
					["name"] = "Millis",
					["date"] = "04/14/07 01:17:20",
					["honor"] = 0,
					["time"] = 1176535040,
					["bg"] = 1,
					["rank"] = "",
				},
				[5012] = {
					["realm"] = "Kel'Thuzad",
					["guild"] = "RedPheonixClan",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Rogue",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 2,
					["race"] = "Blood Elf",
					["time"] = 1175495557,
					["date"] = "04/02/07 00:32:37",
					["honor"] = 0,
					["name"] = "Mistienna",
					["bg"] = 1,
					["rank"] = "",
				},
				[5076] = {
					["realm"] = "Altar of Storms",
					["guild"] = "Dark Tide",
					["zone"] = "Arathi Basin",
					["subzone"] = "Lumber Mill",
					["class"] = "Paladin",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Stormbringer",
					["date"] = "04/14/07 01:17:27",
					["honor"] = 0,
					["time"] = 1176535047,
					["bg"] = 1,
					["rank"] = "",
				},
				[5013] = {
					["realm"] = "Icecrown",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Warlock",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Blood Elf",
					["time"] = 1175495568,
					["date"] = "04/02/07 00:32:48",
					["honor"] = 1,
					["name"] = "Delanthalas",
					["bg"] = 1,
					["rank"] = "",
				},
				[5077] = {
					["realm"] = "Altar of Storms",
					["guild"] = "Dark Tide",
					["zone"] = "Arathi Basin",
					["subzone"] = "Lumber Mill",
					["class"] = "Paladin",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Stormbringer",
					["date"] = "04/14/07 01:18:57",
					["honor"] = 4,
					["time"] = 1176535137,
					["bg"] = 1,
					["rank"] = "",
				},
				[5014] = {
					["realm"] = "Icecrown",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Warlock",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Blood Elf",
					["time"] = 1175495577,
					["date"] = "04/02/07 00:32:57",
					["honor"] = 1,
					["name"] = "Delanthalas",
					["bg"] = 1,
					["rank"] = "",
				},
				[5078] = {
					["realm"] = "Tanaris",
					["guild"] = "ACROSS",
					["zone"] = "Arathi Basin",
					["subzone"] = "Lumber Mill",
					["class"] = "Shaman",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 2,
					["race"] = "Orc",
					["name"] = "Placmatheo",
					["date"] = "04/14/07 01:19:36",
					["honor"] = 0,
					["time"] = 1176535176,
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5015] = {
					["realm"] = "Alterac Mountains",
					["guild"] = "Scandalous",
					["zone"] = "Arathi Basin",
					["subzone"] = "Gold Mine",
					["class"] = "Hunter",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 3,
					["race"] = "Blood Elf",
					["time"] = 1175495641,
					["date"] = "04/02/07 00:34:01",
					["honor"] = 1,
					["name"] = "Faelynn",
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5079] = {
					["win"] = 0,
					["zone"] = "Tanaris",
					["subzone"] = "Gadgetzan",
					["class"] = "Shaman",
					["date"] = "05/01/07 02:20:53",
					["enemy"] = 0,
					["name"] = "Rider",
					["race"] = "Draenei",
					["time"] = 1178007653,
					["guild"] = "Forsaken Destiny",
					["honor"] = 0,
					["lvlDiff"] = 1,
					["bg"] = 0,
					["rank"] = "",
				},
				[5016] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "Hellraisers",
					["zone"] = "Arathi Basin",
					["subzone"] = "Blacksmith",
					["class"] = "Mage",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 3,
					["race"] = "Undead",
					["time"] = 1175495738,
					["date"] = "04/02/07 00:35:38",
					["honor"] = 0,
					["name"] = "Logical",
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5017] = {
					["win"] = 1,
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Warlock",
					["date"] = "04/02/07 00:42:28",
					["enemy"] = 1,
					["name"] = "Nyphestis",
					["race"] = "Blood Elf",
					["time"] = 1175496148,
					["guild"] = "Order Of Royal Blood",
					["honor"] = 0,
					["lvlDiff"] = 3,
					["bg"] = 1,
					["rank"] = "",
				},
				[5018] = {
					["realm"] = "Aerie Peak",
					["guild"] = "Thralls Elite",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Warrior",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 0,
					["race"] = "Orc",
					["time"] = 1175496160,
					["date"] = "04/02/07 00:42:40",
					["honor"] = 1,
					["name"] = "Dschlickone",
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5019] = {
					["realm"] = "Demon Soul",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Warlock",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 2,
					["race"] = "Orc",
					["time"] = 1175496243,
					["date"] = "04/02/07 00:44:03",
					["honor"] = 1,
					["name"] = "Riyin",
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5020] = {
					["realm"] = "Icecrown",
					["guild"] = "Vindicatum",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Warrior",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 0,
					["race"] = "Tauren",
					["time"] = 1175496291,
					["date"] = "04/02/07 00:44:51",
					["honor"] = 2,
					["name"] = "Ethanatos",
					["bg"] = 1,
					["rank"] = "",
				},
				[5021] = {
					["realm"] = "The Venture Co",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Shaman",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Tauren",
					["time"] = 1175496309,
					["date"] = "04/02/07 00:45:09",
					["honor"] = 0,
					["name"] = "Spiritblaze",
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5022] = {
					["realm"] = "Demon Soul",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Warlock",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 2,
					["race"] = "Orc",
					["time"] = 1175496391,
					["date"] = "04/02/07 00:46:31",
					["honor"] = 1,
					["name"] = "Riyin",
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5023] = {
					["realm"] = "Icecrown",
					["guild"] = "Vindicatum",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Warrior",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 0,
					["race"] = "Tauren",
					["time"] = 1175496406,
					["date"] = "04/02/07 00:46:46",
					["honor"] = 1,
					["name"] = "Ethanatos",
					["bg"] = 1,
					["rank"] = "",
				},
				[5024] = {
					["realm"] = "Kel'Thuzad",
					["guild"] = "RedPheonixClan",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Rogue",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 2,
					["race"] = "Blood Elf",
					["time"] = 1175496455,
					["date"] = "04/02/07 00:47:35",
					["honor"] = 0,
					["name"] = "Mistienna",
					["bg"] = 1,
					["rank"] = "",
				},
				[5025] = {
					["realm"] = "Deathwing",
					["guild"] = "Shadow Syndicate",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Paladin",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = -2,
					["race"] = "Blood Elf",
					["time"] = 1175496525,
					["date"] = "04/02/07 00:48:45",
					["honor"] = 0,
					["name"] = "Zavas",
					["bg"] = 1,
					["rank"] = "",
				},
				[5026] = {
					["realm"] = "Kel'Thuzad",
					["guild"] = "RedPheonixClan",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Rogue",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 2,
					["race"] = "Blood Elf",
					["time"] = 1175496556,
					["date"] = "04/02/07 00:49:16",
					["honor"] = 1,
					["name"] = "Mistienna",
					["bg"] = 1,
					["rank"] = "",
				},
				[5027] = {
					["realm"] = "Icecrown",
					["guild"] = "Vindicatum",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Warrior",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 0,
					["race"] = "Tauren",
					["time"] = 1175496612,
					["date"] = "04/02/07 00:50:12",
					["honor"] = 3,
					["name"] = "Ethanatos",
					["bg"] = 1,
					["rank"] = "",
				},
				[5028] = {
					["win"] = 0,
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Rogue",
					["date"] = "04/02/07 00:50:17",
					["enemy"] = 1,
					["name"] = "Anubisx",
					["race"] = "Undead",
					["time"] = 1175496617,
					["guild"] = "",
					["honor"] = 0,
					["lvlDiff"] = 3,
					["bg"] = 1,
					["rank"] = "Sergeant",
				},
				[5029] = {
					["rank"] = "",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Lumber Mill",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["time"] = 1175568311,
					["race"] = "Orc",
					["name"] = "Rekrisha",
					["honor"] = 0,
					["date"] = "04/02/07 20:45:11",
					["lvlDiff"] = -2,
					["bg"] = 1,
					["realm"] = "Altar of Storms",
				},
				[5030] = {
					["rank"] = "",
					["guild"] = "Roughnecks",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Druid",
					["win"] = 0,
					["enemy"] = 1,
					["time"] = 1175568386,
					["race"] = "Tauren",
					["name"] = "Camotree",
					["honor"] = 0,
					["date"] = "04/02/07 20:46:26",
					["lvlDiff"] = 2,
					["bg"] = 1,
					["realm"] = "Blackwing Lair",
				},
				[5031] = {
					["rank"] = "",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Lumber Mill",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["time"] = 1175568830,
					["race"] = "Orc",
					["name"] = "Rekrisha",
					["honor"] = 0,
					["date"] = "04/02/07 20:53:50",
					["lvlDiff"] = -2,
					["bg"] = 1,
					["realm"] = "Altar of Storms",
				},
				[5032] = {
					["win"] = 1,
					["zone"] = "Arathi Highlands",
					["subzone"] = "Go'Shek Farm",
					["class"] = "Rogue",
					["date"] = "04/05/07 19:29:33",
					["enemy"] = 0,
					["time"] = 1175822973,
					["race"] = "Troll",
					["name"] = "Jaezred",
					["lvlDiff"] = 0,
					["honor"] = 0,
					["guild"] = "Icy Death",
					["bg"] = 0,
					["rank"] = "",
				},
				[5033] = {
					["guild"] = "",
					["zone"] = "Arathi Highlands",
					["subzone"] = "Stromgarde Keep",
					["class"] = "Mage",
					["enemy"] = 1,
					["date"] = "04/11/07 21:40:44",
					["time"] = 1176349244,
					["name"] = "Abaloz",
					["win"] = 1,
					["honor"] = 0,
					["lvlDiff"] = 2,
					["bg"] = 0,
					["rank"] = "",
				},
				[5034] = {
					["realm"] = "Demon Soul",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Rogue",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Lahx",
					["date"] = "04/14/07 00:23:23",
					["honor"] = 0,
					["time"] = 1176531803,
					["bg"] = 1,
					["rank"] = "",
				},
				[5035] = {
					["win"] = 1,
					["zone"] = "Arathi Basin",
					["subzone"] = "Gold Mine",
					["class"] = "Hunter",
					["date"] = "04/14/07 00:23:46",
					["enemy"] = 1,
					["name"] = "Scallywag",
					["race"] = "Blood Elf",
					["time"] = 1176531826,
					["guild"] = "",
					["honor"] = 2,
					["lvlDiff"] = 6,
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5036] = {
					["realm"] = "Sentinels",
					["guild"] = "House Extaminos",
					["zone"] = "Arathi Basin",
					["subzone"] = "Gold Mine",
					["class"] = "Paladin",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 7,
					["race"] = "Blood Elf",
					["name"] = "Maximos",
					["date"] = "04/14/07 00:23:57",
					["honor"] = 2,
					["time"] = 1176531837,
					["bg"] = 1,
					["rank"] = "",
				},
				[5037] = {
					["realm"] = "Demon Soul",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Gold Mine",
					["class"] = "Rogue",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Lahx",
					["date"] = "04/14/07 00:24:23",
					["honor"] = 0,
					["time"] = 1176531863,
					["bg"] = 1,
					["rank"] = "",
				},
				[5038] = {
					["win"] = 1,
					["zone"] = "Arathi Basin",
					["subzone"] = "Gold Mine",
					["class"] = "Hunter",
					["date"] = "04/14/07 00:24:40",
					["enemy"] = 1,
					["name"] = "Scallywag",
					["race"] = "Blood Elf",
					["time"] = 1176531880,
					["guild"] = "",
					["honor"] = 2,
					["lvlDiff"] = 6,
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5039] = {
					["realm"] = "Altar of Storms",
					["guild"] = "Three Lobed Burning Eye",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Warrior",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Tauren",
					["name"] = "Murderbull",
					["date"] = "04/14/07 00:26:17",
					["honor"] = 0,
					["time"] = 1176531977,
					["bg"] = 1,
					["rank"] = "",
				},
				[5040] = {
					["win"] = 1,
					["zone"] = "Arathi Basin",
					["subzone"] = "Blacksmith",
					["class"] = "Hunter",
					["date"] = "04/14/07 00:27:08",
					["enemy"] = 1,
					["name"] = "Scallywag",
					["race"] = "Blood Elf",
					["time"] = 1176532028,
					["guild"] = "",
					["honor"] = 3,
					["lvlDiff"] = 6,
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5041] = {
					["win"] = 0,
					["zone"] = "Arathi Basin",
					["subzone"] = "Blacksmith",
					["class"] = "Hunter",
					["date"] = "04/14/07 00:27:09",
					["enemy"] = 1,
					["name"] = "Scallywag",
					["race"] = "Blood Elf",
					["time"] = 1176532029,
					["guild"] = "",
					["honor"] = 0,
					["lvlDiff"] = 6,
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5042] = {
					["realm"] = "Demon Soul",
					["guild"] = "Ghostnation",
					["zone"] = "Arathi Basin",
					["subzone"] = "Farm",
					["class"] = "Priest",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 7,
					["race"] = "Blood Elf",
					["name"] = "Mythology",
					["date"] = "04/14/07 00:28:40",
					["honor"] = 0,
					["time"] = 1176532120,
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5043] = {
					["realm"] = "Kel'Thuzad",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Druid",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 7,
					["race"] = "Tauren",
					["name"] = "Meatnormus",
					["date"] = "04/14/07 00:31:45",
					["honor"] = 0,
					["time"] = 1176532305,
					["bg"] = 1,
					["rank"] = "Senior Sergeant",
				},
				[5044] = {
					["realm"] = "Demon Soul",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Farm",
					["class"] = "Priest",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 2,
					["race"] = "Undead",
					["name"] = "Popeloui",
					["date"] = "04/14/07 00:33:31",
					["honor"] = 3,
					["time"] = 1176532411,
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5045] = {
					["realm"] = "Altar of Storms",
					["guild"] = "Three Lobed Burning Eye",
					["zone"] = "Arathi Basin",
					["subzone"] = "Farm",
					["class"] = "Warrior",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Tauren",
					["name"] = "Murderbull",
					["date"] = "04/14/07 00:33:52",
					["honor"] = 0,
					["time"] = 1176532432,
					["bg"] = 1,
					["rank"] = "",
				},
				[5046] = {
					["realm"] = "Anvilmar",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Priest",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 7,
					["race"] = "Undead",
					["name"] = "Arri",
					["date"] = "04/14/07 00:35:08",
					["honor"] = 1,
					["time"] = 1176532508,
					["bg"] = 1,
					["rank"] = "Senior Sergeant",
				},
				[5047] = {
					["realm"] = "Demon Soul",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Lumber Mill",
					["class"] = "Rogue",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Lahx",
					["date"] = "04/14/07 00:36:29",
					["honor"] = 0,
					["time"] = 1176532589,
					["bg"] = 1,
					["rank"] = "",
				},
				[5048] = {
					["realm"] = "Demon Soul",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Blacksmith",
					["class"] = "Rogue",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Lahx",
					["date"] = "04/14/07 00:38:21",
					["honor"] = 0,
					["time"] = 1176532701,
					["bg"] = 1,
					["rank"] = "",
				},
				[5049] = {
					["win"] = 1,
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Paladin",
					["date"] = "04/14/07 00:43:44",
					["enemy"] = 1,
					["name"] = "Katko",
					["race"] = "Blood Elf",
					["time"] = 1176533024,
					["guild"] = "Flesh Peddlers",
					["honor"] = 2,
					["lvlDiff"] = 2,
					["bg"] = 1,
					["rank"] = "Senior Sergeant",
				},
				[5050] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Blood Elf",
					["name"] = "Darkjmont",
					["date"] = "04/14/07 00:44:21",
					["honor"] = 0,
					["time"] = 1176533061,
					["bg"] = 1,
					["rank"] = "",
				},
				[5051] = {
					["realm"] = "Tanaris",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Paladin",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 7,
					["race"] = "Blood Elf",
					["name"] = "Millis",
					["date"] = "04/14/07 00:44:24",
					["honor"] = 1,
					["time"] = 1176533064,
					["bg"] = 1,
					["rank"] = "",
				},
				[5052] = {
					["realm"] = "Altar of Storms",
					["guild"] = "Three Lobed Burning Eye",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Warrior",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Tauren",
					["name"] = "Murderbull",
					["date"] = "04/14/07 00:44:35",
					["honor"] = 1,
					["time"] = 1176533075,
					["bg"] = 1,
					["rank"] = "",
				},
				[5053] = {
					["realm"] = "Jaedenar",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Rogue",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 7,
					["race"] = "Troll",
					["name"] = "Flags",
					["date"] = "04/14/07 00:44:53",
					["honor"] = 0,
					["time"] = 1176533093,
					["bg"] = 1,
					["rank"] = "First Sergeant",
				},
				[5054] = {
					["realm"] = "Tanaris",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Gold Mine",
					["class"] = "Paladin",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 7,
					["race"] = "Blood Elf",
					["name"] = "Millis",
					["date"] = "04/14/07 00:45:45",
					["honor"] = 1,
					["time"] = 1176533145,
					["bg"] = 1,
					["rank"] = "",
				},
				[5055] = {
					["realm"] = "Deathwing",
					["guild"] = "Reckoning",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Troll",
					["name"] = "Hottyhunter",
					["date"] = "04/14/07 00:46:49",
					["honor"] = 0,
					["time"] = 1176533209,
					["bg"] = 1,
					["rank"] = "",
				},
				[5056] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Blood Elf",
					["name"] = "Darkjmont",
					["date"] = "04/14/07 00:49:01",
					["honor"] = 0,
					["time"] = 1176533341,
					["bg"] = 1,
					["rank"] = "",
				},
				[5057] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Blood Elf",
					["name"] = "Darkjmont",
					["date"] = "04/14/07 00:50:43",
					["honor"] = 0,
					["time"] = 1176533443,
					["bg"] = 1,
					["rank"] = "",
				},
				[5058] = {
					["realm"] = "Alterac Mountains",
					["guild"] = "Blood Line",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Mage",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Illian",
					["date"] = "04/14/07 00:51:40",
					["honor"] = 0,
					["time"] = 1176533500,
					["bg"] = 1,
					["rank"] = "",
				},
				[5059] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Blood Elf",
					["name"] = "Darkjmont",
					["date"] = "04/14/07 00:51:47",
					["honor"] = 0,
					["time"] = 1176533507,
					["bg"] = 1,
					["rank"] = "",
				},
				[5060] = {
					["realm"] = "Demon Soul",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Rogue",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Lahx",
					["date"] = "04/14/07 00:52:29",
					["honor"] = 0,
					["time"] = 1176533549,
					["bg"] = 1,
					["rank"] = "",
				},
				[5061] = {
					["realm"] = "Demon Soul",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Rogue",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Lahx",
					["date"] = "04/14/07 00:54:15",
					["honor"] = 0,
					["time"] = 1176533655,
					["bg"] = 1,
					["rank"] = "",
				},
				[5062] = {
					["realm"] = "Aerie Peak",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Mage",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 7,
					["race"] = "Troll",
					["name"] = "Divo",
					["date"] = "04/14/07 00:54:28",
					["honor"] = 0,
					["time"] = 1176533668,
					["bg"] = 1,
					["rank"] = "First Sergeant",
				},
				[5063] = {
					["realm"] = "Deathwing",
					["guild"] = "Reckoning",
					["zone"] = "Arathi Basin",
					["subzone"] = "Stables",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Troll",
					["name"] = "Hottyhunter",
					["date"] = "04/14/07 00:56:32",
					["honor"] = 0,
					["time"] = 1176533792,
					["bg"] = 1,
					["rank"] = "",
				},
				[5000] = {
					["win"] = 1,
					["zone"] = "Duskwood",
					["subzone"] = "Darkshire",
					["class"] = "Paladin",
					["date"] = "03/26/07 00:02:12",
					["enemy"] = 0,
					["time"] = 1174888932,
					["race"] = "Human",
					["name"] = "Peytonm",
					["lvlDiff"] = -3,
					["honor"] = 0,
					["guild"] = "Protectors of the Light",
					["bg"] = 0,
					["rank"] = "",
				},
				[5064] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Blood Elf",
					["name"] = "Darkjmont",
					["date"] = "04/14/07 00:58:07",
					["honor"] = 0,
					["time"] = 1176533887,
					["bg"] = 1,
					["rank"] = "",
				},
				[5001] = {
					["win"] = 0,
					["zone"] = "Arathi Highlands",
					["subzone"] = "Refuge Pointe",
					["class"] = "Rogue",
					["date"] = "03/29/07 02:46:12",
					["enemy"] = 0,
					["name"] = "Anghelic",
					["race"] = "Gnome",
					["time"] = 1175157972,
					["guild"] = "Tier Zero",
					["honor"] = 0,
					["lvlDiff"] = 1,
					["bg"] = 0,
					["rank"] = "",
				},
				[5065] = {
					["realm"] = "Deathwing",
					["guild"] = "Reckoning",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Troll",
					["name"] = "Hottyhunter",
					["date"] = "04/14/07 00:58:16",
					["honor"] = 0,
					["time"] = 1176533896,
					["bg"] = 1,
					["rank"] = "",
				},
				[5002] = {
					["realm"] = "Undermine",
					["guild"] = "Mounties",
					["zone"] = "Arathi Basin",
					["subzone"] = "Blacksmith",
					["class"] = "Warlock",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 5,
					["race"] = "Undead",
					["time"] = 1175158692,
					["date"] = "03/29/07 02:58:12",
					["honor"] = 0,
					["name"] = "Anybody",
					["bg"] = 1,
					["rank"] = "",
				},
				[5066] = {
					["realm"] = "Alterac Mountains",
					["guild"] = "Blood Line",
					["zone"] = "Arathi Basin",
					["subzone"] = "Trollbane Hall",
					["class"] = "Mage",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Illian",
					["date"] = "04/14/07 00:58:44",
					["honor"] = 1,
					["time"] = 1176533924,
					["bg"] = 1,
					["rank"] = "",
				},
				[5003] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "Pandemonium",
					["zone"] = "Arathi Basin",
					["subzone"] = "Blacksmith",
					["class"] = "Warlock",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 4,
					["race"] = "Blood Elf",
					["time"] = 1175158709,
					["date"] = "03/29/07 02:58:29",
					["honor"] = 1,
					["name"] = "Rainbowsftw",
					["bg"] = 1,
					["rank"] = "Scout",
				},
				[5067] = {
					["realm"] = "Altar of Storms",
					["guild"] = "Three Lobed Burning Eye",
					["zone"] = "Arathi Basin",
					["subzone"] = "Trollbane Hall",
					["class"] = "Warrior",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Tauren",
					["name"] = "Murderbull",
					["date"] = "04/14/07 00:59:02",
					["honor"] = 2,
					["time"] = 1176533942,
					["bg"] = 1,
					["rank"] = "",
				},
				[5004] = {
					["rank"] = "",
					["guild"] = "Sweaty and ready",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Druid",
					["win"] = 1,
					["enemy"] = 1,
					["time"] = 1175158881,
					["race"] = "Tauren",
					["name"] = "Sprowthelas",
					["honor"] = 0,
					["date"] = "03/29/07 03:01:21",
					["lvlDiff"] = -2,
					["bg"] = 1,
					["realm"] = "Jaedenar",
				},
				[5068] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Blood Elf",
					["name"] = "Darkjmont",
					["date"] = "04/14/07 01:04:41",
					["honor"] = 0,
					["time"] = 1176534281,
					["bg"] = 1,
					["rank"] = "",
				},
				[5005] = {
					["rank"] = "Scout",
					["guild"] = "Pandemonium",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Warlock",
					["win"] = 0,
					["enemy"] = 1,
					["time"] = 1175159099,
					["race"] = "Blood Elf",
					["name"] = "Rainbowsftw",
					["honor"] = 0,
					["date"] = "03/29/07 03:04:59",
					["lvlDiff"] = 4,
					["bg"] = 1,
					["realm"] = "Blackwing Lair",
				},
				[5069] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Blood Elf",
					["name"] = "Darkjmont",
					["date"] = "04/14/07 01:06:46",
					["honor"] = 0,
					["time"] = 1176534406,
					["bg"] = 1,
					["rank"] = "",
				},
				[5006] = {
					["rank"] = "Scout",
					["guild"] = "Pandemonium",
					["zone"] = "Arathi Basin",
					["subzone"] = "Blacksmith",
					["class"] = "Warlock",
					["win"] = 0,
					["enemy"] = 1,
					["time"] = 1175159265,
					["race"] = "Blood Elf",
					["name"] = "Rainbowsftw",
					["honor"] = 0,
					["date"] = "03/29/07 03:07:45",
					["lvlDiff"] = 4,
					["bg"] = 1,
					["realm"] = "Blackwing Lair",
				},
				[5070] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 1,
					["race"] = "Blood Elf",
					["name"] = "Darkjmont",
					["date"] = "04/14/07 01:08:02",
					["honor"] = 0,
					["time"] = 1176534482,
					["bg"] = 1,
					["rank"] = "",
				},
				[5007] = {
					["rank"] = "Scout",
					["guild"] = "Pandemonium",
					["zone"] = "Arathi Basin",
					["subzone"] = "Blacksmith",
					["class"] = "Warlock",
					["win"] = 0,
					["enemy"] = 1,
					["time"] = 1175159315,
					["race"] = "Blood Elf",
					["name"] = "Rainbowsftw",
					["honor"] = 0,
					["date"] = "03/29/07 03:08:35",
					["lvlDiff"] = 4,
					["bg"] = 1,
					["realm"] = "Blackwing Lair",
				},
				[5071] = {
					["realm"] = "Altar of Storms",
					["guild"] = "Dark Tide",
					["zone"] = "Arathi Basin",
					["subzone"] = "Gold Mine",
					["class"] = "Paladin",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Stormbringer",
					["date"] = "04/14/07 01:09:45",
					["honor"] = 0,
					["time"] = 1176534585,
					["bg"] = 1,
					["rank"] = "",
				},
				[5008] = {
					["rank"] = "",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 1,
					["enemy"] = 1,
					["time"] = 1175159388,
					["race"] = "Tauren",
					["name"] = "Lowlide",
					["honor"] = 1,
					["date"] = "03/29/07 03:09:48",
					["lvlDiff"] = -3,
					["bg"] = 1,
					["realm"] = "Jaedenar",
				},
				[5072] = {
					["realm"] = "Altar of Storms",
					["guild"] = "Three Lobed Burning Eye",
					["zone"] = "Arathi Basin",
					["subzone"] = "Gold Mine",
					["class"] = "Warrior",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Tauren",
					["name"] = "Murderbull",
					["date"] = "04/14/07 01:11:13",
					["honor"] = 2,
					["time"] = 1176534673,
					["bg"] = 1,
					["rank"] = "",
				},
				[5009] = {
					["rank"] = "",
					["guild"] = "Roughnecks",
					["zone"] = "Arathi Basin",
					["subzone"] = "",
					["class"] = "Hunter",
					["win"] = 1,
					["enemy"] = 1,
					["time"] = 1175159498,
					["race"] = "Orc",
					["name"] = "Rewen",
					["honor"] = 1,
					["date"] = "03/29/07 03:11:38",
					["lvlDiff"] = 2,
					["bg"] = 1,
					["realm"] = "Blackwing Lair",
				},
				[5073] = {
					["realm"] = "Altar of Storms",
					["guild"] = "Dark Tide",
					["zone"] = "Arathi Basin",
					["subzone"] = "Gold Mine",
					["class"] = "Paladin",
					["win"] = 1,
					["enemy"] = 1,
					["lvlDiff"] = 6,
					["race"] = "Blood Elf",
					["name"] = "Stormbringer",
					["date"] = "04/14/07 01:12:11",
					["honor"] = 0,
					["time"] = 1176534731,
					["bg"] = 1,
					["rank"] = "",
				},
				[5010] = {
					["rank"] = "",
					["guild"] = "",
					["zone"] = "Arathi Basin",
					["subzone"] = "Farm",
					["class"] = "Warrior",
					["win"] = 0,
					["enemy"] = 1,
					["time"] = 1175159739,
					["race"] = "Orc",
					["name"] = "Gyrrog",
					["honor"] = 0,
					["date"] = "03/29/07 03:15:39",
					["lvlDiff"] = 1,
					["bg"] = 1,
					["realm"] = "The Venture Co",
				},
				[5074] = {
					["realm"] = "Blackwing Lair",
					["guild"] = "Horde of Defiance",
					["zone"] = "Arathi Basin",
					["subzone"] = "Gold Mine",
					["class"] = "Hunter",
					["win"] = 0,
					["enemy"] = 1,
					["lvlDiff"] = 7,
					["race"] = "Blood Elf",
					["name"] = "Tirantha",
					["date"] = "04/14/07 01:13:52",
					["honor"] = 0,
					["time"] = 1176534832,
					["bg"] = 1,
					["rank"] = "",
				},
			},
			["version"] = "2.3.7",
			["vendor"] = "wowroster.net",
		},
	},
}
targetList = {
	"Meatnormus", -- [1]
	"Healster", -- [2]
	"Shakrall", -- [3]
	"Kirsahn", -- [4]
	"Popeloui", -- [5]
	"Arri", -- [6]
	"Katko", -- [7]
	"Millis", -- [8]
	"Illian", -- [9]
	"Darkjmont", -- [10]
	"Flags", -- [11]
	"Divo", -- [12]
	"Hottyhunter", -- [13]
	"Illuminata", -- [14]
	"Amale", -- [15]
	"Xukfu", -- [16]
	"Thronkar", -- [17]
	"Pemmala", -- [18]
	"Stormbringer", -- [19]
	"Earthshakeen", -- [20]
	"Scorpid", -- [21]
	"Lazymage", -- [22]
	"Elervina", -- [23]
	"Placmatheo", -- [24]
	"Sephiros", -- [25]
	"Fistofsteel", -- [26]
	"Supermame", -- [27]
	"Floodfox", -- [28]
	"Guper", -- [29]
	"Gutras", -- [30]
	"Kellorr", -- [31]
	"Kyonasu", -- [32]
	"Crazzydork", -- [33]
	"Evony", -- [34]
	"Atuk", -- [35]
	"Tulox", -- [36]
	"Grounding Totem", -- [37]
	"Hunazzanti", -- [38]
	"Barkenda", -- [39]
	"Calgrenno", -- [40]
	"Chandwaina", -- [41]
	"Qiaga the Keeper", -- [42]
	"Oxina", -- [43]
	"Venture Co. Strip Miner", -- [44]
}
targetRecords = {
	["Kyonasu"] = {
		["race"] = "Tauren",
		["guild"] = "Tarnished Dynasty",
		["level"] = -1,
		["class"] = "Warrior",
		["rank"] = "",
	},
	["Healster"] = {
		["race"] = "Tauren",
		["realm"] = "Kel'Thuzad",
		["level"] = 47,
		["class"] = "Druid",
		["rank"] = "",
	},
	["Xukfu"] = {
		["race"] = "Troll",
		["guild"] = "Instruments of War",
		["realm"] = "Onyxia",
		["level"] = 48,
		["class"] = "Hunter",
		["rank"] = "",
	},
	["Popeloui"] = {
		["race"] = "Undead",
		["realm"] = "Demon Soul",
		["level"] = 44,
		["class"] = "Priest",
		["rank"] = "Scout",
	},
	["Floodfox"] = {
		["race"] = "Orc",
		["guild"] = "Horde of Chaos",
		["level"] = -1,
		["class"] = "Rogue",
		["rank"] = "Blood Guard",
	},
	["Illuminata"] = {
		["race"] = "Blood Elf",
		["guild"] = "Instruments of War",
		["realm"] = "Onyxia",
		["level"] = 47,
		["class"] = "Priest",
		["rank"] = "Scout",
	},
	["Scorpid"] = {
	},
	["Chandwaina"] = {
		["race"] = "Undead",
		["guild"] = "Kegs End",
		["level"] = 42,
		["class"] = "Warlock",
		["rank"] = "",
	},
	["Shakrall"] = {
		["race"] = "Orc",
		["realm"] = "Kel'Thuzad",
		["level"] = 48,
		["class"] = "Warlock",
		["rank"] = "",
	},
	["Amale"] = {
		["race"] = "Undead",
		["realm"] = "Uldaman",
		["level"] = 42,
		["class"] = "Priest",
		["rank"] = "Senior Sergeant",
	},
	["Crazzydork"] = {
		["race"] = "Blood Elf",
		["guild"] = "Red Army",
		["level"] = 47,
		["class"] = "Rogue",
		["rank"] = "",
	},
	["Elervina"] = {
	},
	["Calgrenno"] = {
		["race"] = "Tauren",
		["guild"] = "The Legion of Durotar",
		["level"] = 39,
		["class"] = "Druid",
		["rank"] = "Scout",
	},
	["Pemmala"] = {
		["race"] = "Troll",
		["guild"] = "Dark Pleasures",
		["realm"] = "Tanaris",
		["level"] = 45,
		["class"] = "Hunter",
		["rank"] = "",
	},
	["Lazymage"] = {
	},
	["Divo"] = {
		["race"] = "Troll",
		["realm"] = "Aerie Peak",
		["level"] = 49,
		["class"] = "Mage",
		["rank"] = "First Sergeant",
	},
	["Grounding Totem"] = {
	},
	["Katko"] = {
		["race"] = "Blood Elf",
		["guild"] = "Flesh Peddlers",
		["level"] = 44,
		["class"] = "Paladin",
		["rank"] = "Senior Sergeant",
	},
	["Kellorr"] = {
		["race"] = "Blood Elf",
		["guild"] = "LEGION OF AKILLIZ",
		["level"] = 40,
		["class"] = "Rogue",
		["rank"] = "",
	},
	["Venture Co. Strip Miner"] = {
	},
	["Kirsahn"] = {
		["race"] = "Blood Elf",
		["realm"] = "Aerie Peak",
		["level"] = 49,
		["class"] = "Warlock",
		["rank"] = "",
	},
	["Tulox"] = {
		["race"] = "Orc",
		["guild"] = "Pepper Reborn",
		["level"] = 44,
		["class"] = "Shaman",
		["rank"] = "",
	},
	["Gutras"] = {
		["race"] = "Undead",
		["guild"] = "Arcas Legion",
		["level"] = -1,
		["class"] = "Rogue",
		["rank"] = "Senior Sergeant",
	},
	["Fistofsteel"] = {
		["race"] = "Troll",
		["guild"] = "Lords of Pain",
		["level"] = 43,
		["class"] = "Shaman",
		["rank"] = "Scout",
	},
	["Arri"] = {
		["race"] = "Undead",
		["realm"] = "Anvilmar",
		["level"] = 49,
		["class"] = "Priest",
		["rank"] = "Senior Sergeant",
	},
	["Qiaga the Keeper"] = {
	},
	["Oxina"] = {
		["race"] = "Tauren",
		["guild"] = "Squirrel Legion",
		["level"] = -1,
		["class"] = "Druid",
		["rank"] = "First Sergeant",
	},
	["Meatnormus"] = {
		["race"] = "Tauren",
		["realm"] = "Kel'Thuzad",
		["level"] = 49,
		["class"] = "Druid",
		["rank"] = "Senior Sergeant",
	},
	["Barkenda"] = {
		["race"] = "Undead",
		["guild"] = "Overcast",
		["level"] = 51,
		["class"] = "Rogue",
		["rank"] = "",
	},
	["Earthshakeen"] = {
		["race"] = "Tauren",
		["guild"] = "Nightmare Legion",
		["realm"] = "Anvilmar",
		["level"] = 46,
		["class"] = "Shaman",
		["rank"] = "Scout",
	},
	["Hottyhunter"] = {
		["race"] = "Troll",
		["guild"] = "Reckoning",
		["realm"] = "Deathwing",
		["level"] = 48,
		["class"] = "Hunter",
		["rank"] = "",
	},
	["Illian"] = {
		["race"] = "Blood Elf",
		["guild"] = "Blood Line",
		["realm"] = "Alterac Mountains",
		["level"] = 48,
		["class"] = "Mage",
		["rank"] = "",
	},
	["Millis"] = {
		["race"] = "Blood Elf",
		["realm"] = "Tanaris",
		["level"] = 49,
		["class"] = "Paladin",
		["rank"] = "",
	},
	["Darkjmont"] = {
		["race"] = "Blood Elf",
		["realm"] = "Blackwing Lair",
		["level"] = 43,
		["class"] = "Hunter",
		["rank"] = "",
	},
	["Stormbringer"] = {
		["race"] = "Blood Elf",
		["guild"] = "Dark Tide",
		["realm"] = "Altar of Storms",
		["level"] = 48,
		["class"] = "Paladin",
		["rank"] = "",
	},
	["Thronkar"] = {
		["race"] = "Orc",
		["guild"] = "Bloodbath",
		["realm"] = "Aerie Peak",
		["level"] = 47,
		["class"] = "Warrior",
		["rank"] = "Grunt",
	},
	["Flags"] = {
		["race"] = "Troll",
		["realm"] = "Jaedenar",
		["level"] = 49,
		["class"] = "Rogue",
		["rank"] = "First Sergeant",
	},
	["Evony"] = {
		["race"] = "Blood Elf",
		["guild"] = "Terminus",
		["level"] = 49,
		["class"] = "Paladin",
		["rank"] = "",
	},
	["Hunazzanti"] = {
		["level"] = 47,
		["race"] = "Troll",
		["class"] = "Hunter",
		["rank"] = "",
	},
	["Atuk"] = {
		["race"] = "Tauren",
		["level"] = -1,
		["class"] = "Hunter",
		["rank"] = "",
	},
	["Supermame"] = {
		["race"] = "Undead",
		["guild"] = "LEGION OF AKILLIZ",
		["level"] = 44,
		["class"] = "Rogue",
		["rank"] = "",
	},
	["Guper"] = {
		["race"] = "Troll",
		["guild"] = "Ashes of Darkk Abyss",
		["level"] = -1,
		["class"] = "Hunter",
		["rank"] = "Sergeant",
	},
	["Placmatheo"] = {
		["race"] = "Orc",
		["guild"] = "ACROSS",
		["realm"] = "Tanaris",
		["level"] = 44,
		["class"] = "Shaman",
		["rank"] = "Scout",
	},
	["Sephiros"] = {
		["level"] = 39,
		["race"] = "Blood Elf",
		["class"] = "Paladin",
		["rank"] = "",
	},
}
